name = "ExtendedKronigPennyMatrix"
uuid = "0edef5b7-0e89-49b4-9493-3bcd9a743ed9"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com>"]
version = "0.4.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "1.5.0"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
